### ISSUE TITLE
Bower.io Package error

### ISSUE THREAD

**Issue by SylAr66** [paulrose/bootstrap-select-sass#1]
Hello.
Please excuse my ignorance, I,m fairly new in the world of git-hub, bower etc. 

There is a bower package connected to this repo http://bower.io/search/?q=bootstrap-select-sass , but when I run 

```
bower install bootstrap-select-sass
```

bower_components folder contain bootstrap-select-sass but inside of it there is lees directory not sass

```
ls
bootstrap-select.jquery.json  bower.json  composer.json  CONTRIBUTING.md  dist  Gruntfile.js  js  less  LICENSE  package.json  README.md  test.html
```

**Comment by paulrose** [comment]
Hey @SylAr66 

I didn't know this was listed on the Bower site. I'll sort out this issue for you shortly :)

Paul

**Comment by paulrose** [comment]
@SylAr66 Fixed this now. You might need to do a `bower cache clean` and install again.

Hope it helps!
